#ifndef SOFTAP_UI_H
#define SOFTAP_UI_H

enum softap_state2ui {
	SOFTAP_STATE2UI_WAITTING,
	SOFTAP_STATE2UI_CONNECTED_TO_AP,
	SOFTAP_STATE2UI_DISCONNECTED_FROM_AP
};

typedef struct  
{
	unsigned char   ssid[128+4];
	int                    level;
	int			  num;
}STRUCT_WIFI_SIGN;

#define SOFTAP_UI_MSG_BASE 100

#define SOFTAP_UI_MSG_INIT		(SOFTAP_UI_MSG_BASE + 1)
#define SOFTAP_UI_MSG_STATUS		(SOFTAP_UI_MSG_BASE + 2)
#define SOFTAP_UI_MSG_DEVICE_NAME	(SOFTAP_UI_MSG_BASE + 3)
#define SOFTAP_UI_MSG_IP0		(SOFTAP_UI_MSG_BASE + 4)
#define SOFTAP_UI_MSG_IP1		(SOFTAP_UI_MSG_BASE + 5)
#define SOFTAP_UI_MSG_AP		(SOFTAP_UI_MSG_BASE + 6)
#define SOFTAP_UI_MSG_MODE_SWITCH	(SOFTAP_UI_MSG_BASE + 7)
#define SOFTAP_UI_MSG_UPDATE		(SOFTAP_UI_MSG_BASE + 8)
#define SOFTAP_UI_MSG_PWD		(SOFTAP_UI_MSG_BASE + 9)
#define SOFTAP_UI_MSG_NO_IP		(SOFTAP_UI_MSG_BASE + 10)
#define SOFTAP_UI_MSG_HIDE		(SOFTAP_UI_MSG_BASE + 11)
#define SOFTAP_UI_MSG_SHOW		(SOFTAP_UI_MSG_BASE + 12)
#define SOFTAP_UI_MSG_SHOW_PCBA		(SOFTAP_UI_MSG_BASE + 13)
#define SOFTAP_UI_MSG_PEER_IP		(SOFTAP_UI_MSG_BASE + 14)
#define SOFTAP_UI_MSG_PEER_NAME		(SOFTAP_UI_MSG_BASE + 15)
#define SOFTAP_UI_MSG_CLR_PEER		(SOFTAP_UI_MSG_BASE + 16)

#define SOFTAP_UI_MSG_OTA_NEW_UPDATE		(SOFTAP_UI_MSG_BASE + 201)
#define SOFTAP_UI_MSG_OTA_DOWNLOAD_PERCENT	(SOFTAP_UI_MSG_BASE + 202)
#define SOFTAP_UI_MSG_OTA_DOWNLOAD_COMPLETE	(SOFTAP_UI_MSG_BASE + 203)
#define SOFTAP_UI_MSG_OTA_DOWNLOAD_FAIL		(SOFTAP_UI_MSG_BASE + 204)
#define SOFTAP_UI_MSG_OTA_CHECK_FW_OK		(SOFTAP_UI_MSG_BASE + 205)
#define SOFTAP_UI_MSG_OTA_CHECK_FW_FAIL		(SOFTAP_UI_MSG_BASE + 206)
#define SOFTAP_UI_MSG_OTA_NEW_VERSION		(SOFTAP_UI_MSG_BASE + 207)
#define SOFTAP_UI_MSG_OTA_UI_INIT			(SOFTAP_UI_MSG_BASE + 208)
#define SOFTAP_UI_MSG_OTA_UI_PRE			(SOFTAP_UI_MSG_BASE + 209)
#define SOFTAP_UI_MSG_OTA_UI_PRE_CNT		(SOFTAP_UI_MSG_BASE + 210)
#define SOFTAP_UI_MSG_OTA_UI_PRE_OK			(SOFTAP_UI_MSG_BASE + 211)


#endif //SOFTAP_UI_H
